spring.application.name=plug
app.delay.low_border=1000
app.delay.high_border=2001
app.database.url=jdbc:postgresql://192.168.1.5:5432/plugdb
app.database.user=user
app.dtabase.password=password
management.endpoints.web.exposure.include=prometheus,health,info,metrics
server.tomcat.mbeanregistry.enabled=true
